export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';

export const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// Action Types
export const FETCH_PRESCRIPTIONS_REQUEST = 'FETCH_PRESCRIPTIONS_REQUEST';
export const FETCH_PRESCRIPTIONS_SUCCESS = 'FETCH_PRESCRIPTIONS_SUCCESS';
export const FETCH_PRESCRIPTIONS_FAILURE = 'FETCH_PRESCRIPTIONS_FAILURE';

export const FETCH_DRUGS_TAKEN_RECORD_REQUEST = 'FETCH_DRUGS_TAKEN_RECORD_REQUEST';
export const FETCH_DRUGS_TAKEN_RECORD_SUCCESS = 'FETCH_DRUGS_TAKEN_RECORD_SUCCESS';
export const FETCH_DRUGS_TAKEN_RECORD_FAILURE = 'FETCH_DRUGS_TAKEN_RECORD_FAILURE';
